# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T12:59:09+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr


class Description(RootModel[constr(min_length=1, max_length=2048)]):
    root: constr(min_length=1, max_length=2048)


class DetailStatus(Enum):
    AVAILABLE = 'AVAILABLE'
    PROCESSING = 'PROCESSING'
    UNAVAILABLE = 'UNAVAILABLE'


class Double(RootModel[float]):
    root: float


class FeatureStatus(Enum):
    ENABLED = 'ENABLED'
    DISABLED = 'DISABLED'
    UNSUPPORTED = 'UNSUPPORTED'
    ENABLED_PENDING_REBOOT = 'ENABLED_PENDING_REBOOT'
    DISABLED_PENDING_REBOOT = 'DISABLED_PENDING_REBOOT'
    UNKNOWN = 'UNKNOWN'


class ISOTimestamp(RootModel[datetime]):
    root: datetime


class IdentifierString(
    RootModel[constr(pattern=r'^db-[a-zA-Z0-9-]*$', min_length=0, max_length=256)]
):
    root: constr(pattern=r'^db-[a-zA-Z0-9-]*$', min_length=0, max_length=256)


class Integer(RootModel[int]):
    root: int


class InternalServiceError(RootModel[Any]):
    root: Any


class InvalidArgumentException(RootModel[Any]):
    root: Any


class Limit(RootModel[conint(ge=1, le=25)]):
    root: conint(ge=1, le=25)


class MaxResults(RootModel[conint(ge=0, le=25)]):
    root: conint(ge=0, le=25)


class MetricValuesList(RootModel[List[Double]]):
    root: List[Double]


class NextToken(RootModel[constr(pattern=r'[\s\S]*', min_length=1, max_length=8192)]):
    root: constr(pattern=r'[\s\S]*', min_length=1, max_length=8192)


class NotAuthorizedException(RootModel[Any]):
    root: Any


class PeriodAlignment(Enum):
    END_TIME = 'END_TIME'
    START_TIME = 'START_TIME'


class RequestString(RootModel[constr(pattern=r'.*\S.*', min_length=0, max_length=256)]):
    root: constr(pattern=r'.*\S.*', min_length=0, max_length=256)


class RequestStringList(RootModel[List[RequestString]]):
    root: List[RequestString] = Field(..., max_length=10, min_length=1)


class RequestedDimensionList(RootModel[List[RequestString]]):
    root: List[RequestString] = Field(..., max_length=10, min_length=1)


class ServiceType(Enum):
    RDS = 'RDS'
    DOCDB = 'DOCDB'


class String(RootModel[constr(pattern=r'.*\S.*', min_length=0, max_length=256)]):
    root: constr(pattern=r'.*\S.*', min_length=0, max_length=256)


class XAmzTarget(Enum):
    PerformanceInsightsv20180227_DescribeDimensionKeys = (
        'PerformanceInsightsv20180227.DescribeDimensionKeys'
    )


class XAmzTarget1(Enum):
    PerformanceInsightsv20180227_GetDimensionKeyDetails = (
        'PerformanceInsightsv20180227.GetDimensionKeyDetails'
    )


class XAmzTarget2(Enum):
    PerformanceInsightsv20180227_GetResourceMetadata = (
        'PerformanceInsightsv20180227.GetResourceMetadata'
    )


class XAmzTarget3(Enum):
    PerformanceInsightsv20180227_GetResourceMetrics = (
        'PerformanceInsightsv20180227.GetResourceMetrics'
    )


class XAmzTarget4(Enum):
    PerformanceInsightsv20180227_ListAvailableResourceDimensions = (
        'PerformanceInsightsv20180227.ListAvailableResourceDimensions'
    )


class XAmzTarget5(Enum):
    PerformanceInsightsv20180227_ListAvailableResourceMetrics = (
        'PerformanceInsightsv20180227.ListAvailableResourceMetrics'
    )


class AdditionalMetricsList(RootModel[List[RequestString]]):
    root: List[RequestString] = Field(..., max_length=30, min_length=1)


class AdditionalMetricsMap(RootModel[Optional[Dict[str, Double]]]):
    root: Optional[Dict[str, Double]] = None


class DataPoint(BaseModel):
    Timestamp: ISOTimestamp
    Value: Double


class DataPointsList(RootModel[List[DataPoint]]):
    root: List[DataPoint]


class DimensionDetail(BaseModel):
    Identifier: Optional[String] = None


class DimensionDetailList(RootModel[List[DimensionDetail]]):
    root: List[DimensionDetail]


class DimensionGroup(BaseModel):
    Dimensions: Optional[RequestStringList] = None
    Group: RequestString
    Limit_1: Optional[Limit] = Field(None, alias='Limit')


class DimensionGroupDetail(BaseModel):
    Dimensions: Optional[DimensionDetailList] = None
    Group: Optional[String] = None


class DimensionGroupDetailList(RootModel[List[DimensionGroupDetail]]):
    root: List[DimensionGroupDetail]


class DimensionKeyDetail(BaseModel):
    Dimension: Optional[String] = None
    Status: Optional[DetailStatus] = None
    Value: Optional[String] = None


class DimensionKeyDetailList(RootModel[List[DimensionKeyDetail]]):
    root: List[DimensionKeyDetail]


class DimensionMap(RootModel[Optional[Dict[str, RequestString]]]):
    root: Optional[Dict[str, RequestString]] = None


class DimensionsMetricList(RootModel[List[RequestString]]):
    root: List[RequestString] = Field(..., max_length=5, min_length=1)


class FeatureMetadata(BaseModel):
    Status: Optional[FeatureStatus] = None


class FeatureMetadataMap(RootModel[Optional[Dict[str, FeatureMetadata]]]):
    root: Optional[Dict[str, FeatureMetadata]] = None


class GetDimensionKeyDetailsRequest(BaseModel):
    Group: RequestString
    GroupIdentifier: RequestString
    Identifier: IdentifierString
    RequestedDimensions: Optional[RequestedDimensionList] = None
    ServiceType_1: ServiceType = Field(..., alias='ServiceType')


class GetDimensionKeyDetailsResponse(BaseModel):
    Dimensions: Optional[DimensionKeyDetailList] = None


class GetResourceMetadataRequest(BaseModel):
    Identifier: RequestString
    ServiceType_1: ServiceType = Field(..., alias='ServiceType')


class GetResourceMetadataResponse(BaseModel):
    Features: Optional[FeatureMetadataMap] = None
    Identifier: Optional[String] = None


class ListAvailableResourceDimensionsRequest(BaseModel):
    Identifier: RequestString
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    Metrics: DimensionsMetricList
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    ServiceType_1: ServiceType = Field(..., alias='ServiceType')


class MetricDimensionGroups(BaseModel):
    Groups: Optional[DimensionGroupDetailList] = None
    Metric: Optional[String] = None


class MetricDimensionsList(RootModel[List[MetricDimensionGroups]]):
    root: List[MetricDimensionGroups]


class MetricQueryFilterMap(RootModel[Optional[Dict[str, RequestString]]]):
    root: Optional[Dict[str, RequestString]] = None


class MetricTypeList(RootModel[List[RequestString]]):
    root: List[RequestString]


class ResponsePartitionKey(BaseModel):
    Dimensions: DimensionMap


class ResponsePartitionKeyList(RootModel[List[ResponsePartitionKey]]):
    root: List[ResponsePartitionKey]


class ResponseResourceMetric(BaseModel):
    Description_1: Optional[Description] = Field(None, alias='Description')
    Metric: Optional[String] = None
    Unit: Optional[String] = None


class ResponseResourceMetricKey(BaseModel):
    Dimensions: Optional[DimensionMap] = None
    Metric: String


class ResponseResourceMetricList(RootModel[List[ResponseResourceMetric]]):
    root: List[ResponseResourceMetric]


class DescribeDimensionKeysRequest(BaseModel):
    AdditionalMetrics: Optional[AdditionalMetricsList] = None
    EndTime: ISOTimestamp
    Filter: Optional[MetricQueryFilterMap] = None
    GroupBy: DimensionGroup
    Identifier: RequestString
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    Metric: RequestString
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    PartitionBy: Optional[DimensionGroup] = None
    PeriodInSeconds: Optional[Integer] = None
    ServiceType_1: ServiceType = Field(..., alias='ServiceType')
    StartTime: ISOTimestamp


class DimensionKeyDescription(BaseModel):
    AdditionalMetrics: Optional[AdditionalMetricsMap] = None
    Dimensions: Optional[DimensionMap] = None
    Partitions: Optional[MetricValuesList] = None
    Total: Optional[Double] = None


class DimensionKeyDescriptionList(RootModel[List[DimensionKeyDescription]]):
    root: List[DimensionKeyDescription]


class ListAvailableResourceDimensionsResponse(BaseModel):
    MetricDimensions: Optional[MetricDimensionsList] = None
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')


class ListAvailableResourceMetricsRequest(BaseModel):
    Identifier: RequestString
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    MetricTypes: MetricTypeList
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    ServiceType_1: ServiceType = Field(..., alias='ServiceType')


class ListAvailableResourceMetricsResponse(BaseModel):
    Metrics: Optional[ResponseResourceMetricList] = None
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')


class MetricKeyDataPoints(BaseModel):
    DataPoints: Optional[DataPointsList] = None
    Key: Optional[ResponseResourceMetricKey] = None


class MetricKeyDataPointsList(RootModel[List[MetricKeyDataPoints]]):
    root: List[MetricKeyDataPoints]


class MetricQuery(BaseModel):
    Filter: Optional[MetricQueryFilterMap] = None
    GroupBy: Optional[DimensionGroup] = None
    Metric: RequestString


class MetricQueryList(RootModel[List[MetricQuery]]):
    root: List[MetricQuery] = Field(..., max_length=15, min_length=1)


class DescribeDimensionKeysResponse(BaseModel):
    AlignedEndTime: Optional[ISOTimestamp] = None
    AlignedStartTime: Optional[ISOTimestamp] = None
    Keys: Optional[DimensionKeyDescriptionList] = None
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    PartitionKeys: Optional[ResponsePartitionKeyList] = None


class GetResourceMetricsRequest(BaseModel):
    EndTime: ISOTimestamp
    Identifier: RequestString
    MaxResults_1: Optional[MaxResults] = Field(None, alias='MaxResults')
    MetricQueries: MetricQueryList
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
    PeriodAlignment_1: Optional[PeriodAlignment] = Field(None, alias='PeriodAlignment')
    PeriodInSeconds: Optional[Integer] = None
    ServiceType_1: ServiceType = Field(..., alias='ServiceType')
    StartTime: ISOTimestamp


class GetResourceMetricsResponse(BaseModel):
    AlignedEndTime: Optional[ISOTimestamp] = None
    AlignedStartTime: Optional[ISOTimestamp] = None
    Identifier: Optional[String] = None
    MetricList: Optional[MetricKeyDataPointsList] = None
    NextToken_1: Optional[NextToken] = Field(None, alias='NextToken')
